### ISSUE TITLE
Bot doesn't respond on !configure

### ISSUE THREAD

**Issue by Tofuraven** [DionGR/Discord-Role-Manager#1]
The bot linked in the "installation" section does not respond if provided with a valid spreadsheet ID in the "!configure" step.
The reason might be an exception thrown when trying to create or edit a server file in the database - there's no further exception handling inside the FileNotFoundError catch block.

(Also, it might be preferable to join the "serverdata" directory as an additional parameter instead of using a hard coded backslash for the file paths, to make the code more platform-independent.)

**Comment by DionGR** [comment]
Hello and thanks for your feedback, it is appreciated!

I will work on this and get back to this Issue as soon as I have solved it.

**Comment by DionGR** [comment]
I adjusted how file opening is handled in the code, updated the BOT and tested it. Everything should be working as intended now.
