### ISSUE TITLE
Commands are not working in discord to setup

### ISSUE THREAD

**Issue by BRKS1** [DionGR/Discord-Role-Manager#2]
The bot has correct permissions in the server and is not responding to the commands

**Comment by DionGR** [comment]
Works fine for me. Make sure you are using the correct prefix (!) and there are no conflicts with other bots, as well as that **you** have the necessary permissions.

**Comment by BRKS1** [comment]
It does not work, no other bot has the same command so nothing is triggered

**Comment by DionGR** [comment]
> It does not work, no other bot has the same command so nothing is triggered

The bot is not being hosted by me anymore. If you check it's online status, it should appear offline. I might host it again in the future if need be.


The GitHub page is up only for developers interested in the code. 

I tried it in 2-3 different servers and it worked just fine when self-hosting.


If you wish to use the BOT, set it up as your own for the time being.

**Comment by ibpd02** [comment]
Do you have advice on how to set up the bot as our own for someone who has never made a bot or done coding before? Thanks.

**Comment by DionGR** [comment]
> Do you have advice on how to set up the bot as our own for someone who has never made a bot or done coding before? Thanks.

Watch a tutorial. It will show you how to do basic stuff with code and set it up. 

Then, fork the code and apply the set up part (such as discord tokens etc) to it.
