### ISSUE TITLE
offline

### ISSUE THREAD

**Issue by kakyoins** [DionGR/Discord-Role-Manager#4]

**Comment by DionGR** [comment]
Not related to this GitHub repository in any way.

**Comment by kakyoins** [comment]
you sure? it is offline and doesn't work? none of the commands work

**Comment by DionGR** [comment]
Yes and this repository is for people who wish to self host or find issues in the code, it does not regard whether I am currently hosting the BOT or not. It's not being hosted anywhere at the moment.
